package SignIn.View;

import Message.View.Message_Frame;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.sql.*;

public class SignInFrame extends javax.swing.JFrame {
//              Variable myself!
    
    public static Connection getJDBCConnection()
    {
        final String url = "jdbc:mysql://localhost:3306/login";     
        final String user = "root";
        final String password = "sangxuan153";
        try
        {
//                      Load Driver
            Class.forName("com.mysql.cj.jdbc.Driver");           
//                      Connection URL
//        -> This method returns the object "Connection"
            return  DriverManager.getConnection(url,user,password);
            
        } 
        catch(Exception e)
        {
            System.out.println(e);
        }
        return null;
    }
    public void initMyself()
    {
        lb_notification.setVisible(false);
        pf_password.setEchoChar((char) 0);    
    }
    public SignInFrame() {
        initComponents();
        initMyself();
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        MessageImage = new javax.swing.JLabel();
        NameApp = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        rightPanel = new javax.swing.JPanel();
        icon_username = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lb_login = new javax.swing.JLabel();
        icon_password = new javax.swing.JLabel();
        pf_password = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        lb_close = new javax.swing.JLabel();
        pnl_signin = new javax.swing.JPanel();
        lb_signin = new javax.swing.JLabel();
        pnl_signup = new javax.swing.JPanel();
        lb_signup = new javax.swing.JLabel();
        lb_notification = new javax.swing.JLabel();
        chb_display_password = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        leftPanel.setBackground(new java.awt.Color(255, 255, 255));

        MessageImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MessageImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignIn/View/chat.png"))); // NOI18N

        NameApp.setBackground(new java.awt.Color(51, 51, 255));
        NameApp.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        NameApp.setForeground(new java.awt.Color(51, 51, 255));
        NameApp.setText("Chat With Me!");

        jSeparator1.setForeground(new java.awt.Color(51, 51, 255));
        jSeparator1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        rightPanel.setBackground(new java.awt.Color(51, 153, 255));

        icon_username.setBackground(new java.awt.Color(255, 255, 255));
        icon_username.setFont(new java.awt.Font("Urdu Typesetting", 0, 18)); // NOI18N
        icon_username.setForeground(new java.awt.Color(255, 255, 255));
        icon_username.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignIn/View/user.png"))); // NOI18N

        tf_username.setBackground(new java.awt.Color(51, 153, 255));
        tf_username.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        tf_username.setForeground(new java.awt.Color(255, 255, 255));
        tf_username.setText("User Name");
        tf_username.setBorder(null);
        tf_username.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        tf_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf_usernameFocusLost(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        lb_login.setFont(new java.awt.Font("Urdu Typesetting", 1, 36)); // NOI18N
        lb_login.setForeground(new java.awt.Color(255, 255, 255));
        lb_login.setText("LOG IN");

        icon_password.setFont(new java.awt.Font("Urdu Typesetting", 0, 18)); // NOI18N
        icon_password.setForeground(new java.awt.Color(255, 255, 255));
        icon_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignIn/View/lock.png"))); // NOI18N

        pf_password.setBackground(new java.awt.Color(51, 153, 255));
        pf_password.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pf_password.setForeground(new java.awt.Color(255, 255, 255));
        pf_password.setText("Password");
        pf_password.setBorder(null);
        pf_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pf_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pf_passwordFocusLost(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        lb_close.setFont(new java.awt.Font("Urdu Typesetting", 0, 18)); // NOI18N
        lb_close.setForeground(new java.awt.Color(255, 255, 255));
        lb_close.setText(" X");
        lb_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_closeMouseClicked(evt);
            }
        });

        pnl_signin.setBackground(new java.awt.Color(51, 153, 255));
        pnl_signin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lb_signin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_signin.setForeground(new java.awt.Color(255, 255, 255));
        lb_signin.setText("   Sign In");
        lb_signin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_signinMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_signinMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb_signinMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnl_signinLayout = new javax.swing.GroupLayout(pnl_signin);
        pnl_signin.setLayout(pnl_signinLayout);
        pnl_signinLayout.setHorizontalGroup(
            pnl_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_signinLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_signinLayout.setVerticalGroup(
            pnl_signinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_signinLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_signin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnl_signup.setBackground(new java.awt.Color(51, 153, 255));
        pnl_signup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lb_signup.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_signup.setForeground(new java.awt.Color(255, 255, 255));
        lb_signup.setText("   Sign Up");
        lb_signup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_signupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_signupMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lb_signupMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnl_signupLayout = new javax.swing.GroupLayout(pnl_signup);
        pnl_signup.setLayout(pnl_signupLayout);
        pnl_signupLayout.setHorizontalGroup(
            pnl_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_signupLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnl_signupLayout.setVerticalGroup(
            pnl_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_signupLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lb_signup, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lb_notification.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lb_notification.setForeground(new java.awt.Color(255, 0, 0));
        lb_notification.setText("Do you forget password?");

        chb_display_password.setBackground(new java.awt.Color(51, 153, 255));
        chb_display_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chb_display_password.setForeground(new java.awt.Color(255, 255, 255));
        chb_display_password.setText("Show your password");
        chb_display_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chb_display_passwordMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(icon_username)
                            .addComponent(icon_password))
                        .addGap(27, 27, 27)
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chb_display_password, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(tf_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(pnl_signup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(pnl_signin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                        .addComponent(lb_login)
                        .addGap(89, 89, 89)
                        .addComponent(lb_close, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                        .addComponent(lb_notification)
                        .addGap(22, 22, 22))))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_close, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_login))
                .addGap(25, 25, 25)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon_username))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pf_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icon_password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chb_display_password)
                .addGap(30, 30, 30)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_signin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_signup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lb_notification)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(NameApp, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MessageImage, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(rightPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(NameApp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(MessageImage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lb_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lb_closeMouseClicked

    private void tf_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_usernameFocusGained
        tf_username.setText("");
    }//GEN-LAST:event_tf_usernameFocusGained

    private void pf_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pf_passwordFocusGained
        pf_password.setText("");
        if (chb_display_password.isSelected())
       {
           pf_password.setEchoChar((char)0);
       }
       else
       {
           pf_password.setEchoChar('\u25CF');
       }
    }//GEN-LAST:event_pf_passwordFocusGained

    private void lb_signupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_signupMouseEntered
        lb_signup.setForeground(new Color(51,153,255));
        pnl_signup.setBackground(Color.white);
    }//GEN-LAST:event_lb_signupMouseEntered

    private void lb_signupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_signupMouseExited
        lb_signup.setForeground(Color.white);
        pnl_signup.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_lb_signupMouseExited

    private void lb_signinMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_signinMouseEntered
        lb_signin.setForeground(new Color(51,153,255));
        pnl_signin.setBackground(Color.white);
    }//GEN-LAST:event_lb_signinMouseEntered

    private void lb_signinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_signinMouseExited
        lb_signin.setForeground(Color.white);
        pnl_signin.setBackground(new Color(51,153,255));
    }//GEN-LAST:event_lb_signinMouseExited

    private void lb_signupMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_signupMousePressed
        int id;
        String user = tf_username.getText();
        String pw   = pf_password.getText();
        Connection connection = SignInFrame.getJDBCConnection();

        try 
        {
            String sql = "select *from form";
            Statement stmt = connection.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
            ResultSet rs = stmt.executeQuery(sql);
            rs.last();
            id = rs.getInt(1);
            rs.absolute(0);
            while(rs.next())
            {
                if(rs.getString(2).equals(user))
                {
                    if(rs.getString(3).equals(pw))
                    {
                        this.dispose();
                        new Message_Frame().setVisible(true);
                        break;
                    }
                }
                if(rs.getInt(1) == id)
                {
                    lb_notification.setText("Do you forget password?");
                    lb_notification.setForeground(Color.red);
                    lb_notification.setVisible(true);
                }
            }
        } 
        catch (SQLException ex) 
        {
            Logger.getLogger(SignInFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lb_signupMousePressed

    private void tf_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_usernameFocusLost
        if (tf_username.getText().equals(""))
        {
            tf_username.setText("User Name");
        }
    }//GEN-LAST:event_tf_usernameFocusLost

    private void lb_signinMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_signinMousePressed
        Connection connection = SignInFrame.getJDBCConnection();
        try {
            Statement stmt = connection.createStatement();
            String sql = "insert into form(username,password) values(?,?)";
            PreparedStatement ps = connection.prepareStatement(sql);
//            ps.setInt(1,1);
            ps.setString(1,tf_username.getText());
            ps.setString(2,pf_password.getText());
            
            ps.executeUpdate();
            stmt.close();
            connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(SignInFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        tf_username.setText("User Name");
        pf_password.setText("Password");
        
        lb_notification.setText("You signed in successfully!");
        lb_notification.setForeground(Color.green);
        lb_notification.setVisible(true);
    }//GEN-LAST:event_lb_signinMousePressed

    private void pf_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pf_passwordFocusLost
        if (pf_password.getText().equals(""))
        {
            pf_password.setText("Password");
        }
        if (chb_display_password.isSelected())
       {
           pf_password.setEchoChar((char)0);
       }
       else
       {
           pf_password.setEchoChar('\u25CF');
       }
    }//GEN-LAST:event_pf_passwordFocusLost

    private void chb_display_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chb_display_passwordMouseClicked
       System.out.println(chb_display_password.isSelected());
       if (chb_display_password.isSelected())
       {
           pf_password.setEchoChar((char)0);
       }
       else
       {
           pf_password.setEchoChar('\u25CF');
       }
    }//GEN-LAST:event_chb_display_passwordMouseClicked

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MessageImage;
    private javax.swing.JLabel NameApp;
    private javax.swing.JCheckBox chb_display_password;
    private javax.swing.JLabel icon_password;
    private javax.swing.JLabel icon_username;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lb_close;
    private javax.swing.JLabel lb_login;
    private javax.swing.JLabel lb_notification;
    private javax.swing.JLabel lb_signin;
    private javax.swing.JLabel lb_signup;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JPanel pnl_signin;
    private javax.swing.JPanel pnl_signup;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
